# Generated by Django 5.0.4 on 2024-04-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnyTimer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("owner_id", models.IntegerField()),
                ("receipient_id", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("type", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
            ],
        ),
    ]
