# Generated by Django 5.0.4 on 2024-04-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anytimer',
            old_name='receipient_id',
            new_name='recipient_id',
        ),
    ]
