# Generated by Django 5.0.4 on 2024-04-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_receipient_id_anytimer_recipient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anytimer',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='anytimer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
