# Generated by Django 5.0.4 on 2024-04-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_anytimerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='anytimer',
            name='owner_name',
            field=models.CharField(default='old', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anytimer',
            name='recipient_name',
            field=models.CharField(default='old', max_length=500),
            preserve_default=False,
        ),
    ]
