# Generated by Django 5.0.4 on 2024-04-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_anytimer_owner_name_anytimer_recipient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='anytimerrequest',
            name='recipient_name',
            field=models.CharField(default='old', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anytimerrequest',
            name='requester_name',
            field=models.CharField(default='old', max_length=500),
            preserve_default=False,
        ),
    ]
