# Generated by Django 5.0.4 on 2024-04-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_anytimerrequest_recipient_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnyTimerProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anytimer_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='proofs/')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('proof_type', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
