# Generated by Django 5.0.4 on 2024-04-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_anytimerproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='anytimer',
            name='status',
            field=models.CharField(choices=[('unused', 'Unused'), ('used', 'Used'), ('completed', 'Completed'), ('accepted', 'Accepted')], default='unused', max_length=10),
        ),
    ]
