# Generated by Django 5.0.4 on 2024-04-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_anytimer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anytimer',
            name='status',
            field=models.CharField(choices=[('unused', 'Unused'), ('used', 'Used'), ('completed', 'Completed')], default='unused', max_length=10),
        ),
    ]
