# Generated by Django 5.0.4 on 2024-04-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_anytimer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anytimerproof',
            name='image',
        ),
        migrations.AddField(
            model_name='anytimerproof',
            name='image_url',
            field=models.CharField(default='old', max_length=500),
            preserve_default=False,
        ),
    ]
