# Generated by Django 5.0.4 on 2024-04-30 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_image_url_anytimerproof_file_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anytimerproof',
            name='file',
        ),
    ]
