# Generated by Django 5.0.4 on 2024-05-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_anytimerproof_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anytimerproof',
            name='file_url',
        ),
        migrations.AddField(
            model_name='anytimerproof',
            name='file',
            field=models.FileField(null=True, upload_to='static/proofs'),
        ),
    ]
