# Generated by Django 5.0.4 on 2024-05-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_anytimerproof_anytimer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anytimerproof',
            old_name='anytimer_id',
            new_name='anytimer',
        ),
    ]
