# Generated by Django 5.0.6 on 2024-05-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_anytimerproof_anytimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anytimerproof',
            name='file',
            field=models.FileField(null=True, upload_to='proofs'),
        ),
    ]
