services:
  server:
    image: ghcr.io/vincevd1/thaliany-server:${TAG:-latest}
    environment:
      SECRET_KEY: ${SECRET_KEY:?Secret key must be set}
      POSTGRES_HOST: postgres
      POSTGRES_DB: thaliany
      POSTGRES_USER: thaliany
      POSTGRES_PASSWORD: thaliany
      SITE_DOMAIN: any.thalia.nu
      BASE_URL: https://any.thalia.nu
      THALIA_BASE_URL: https://thalia.nu
      DEBUG: 0
    volumes:
      - media:/volumes/media:rw
      - static:/volumes/static:rw

  nginx:
    image: ghcr.io/vincevd1/thaliany-nginx:${TAG:-latest}
    environment:
      CERTBOT_EMAIL: thaliany@thalia.nu
      SITE_DOMAIN: any.thalia.nu
    volumes:
      - letsencrypt:/etc/letsencrypt:rw
      - media:/volumes/media:ro
      - static:/volumes/static:ro
    ports:
      - 80:80
      - 443:443

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: thaliany
      POSTGRES_USER: thaliany
      POSTGRES_PASSWORD: thaliany
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  letsencrypt:
  postgres-data:
  media:
  static:
